import WeilDefect.Screening.GraphNormalForm
import Mathlib.Analysis.InnerProductSpace.SingularValues
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.Normed.Module.Bases
import Mathlib

namespace WeilDefect.WDT11

open scoped InnerProduct
open ContinuousLinearMap
open InnerProductSpace
open Module
open WeilDefect.WDT01
open WeilDefect.WDT03

variable {Kpos M : Type*}
variable [NormedAddCommGroup Kpos] [InnerProductSpace ℂ Kpos] [CompleteSpace Kpos]
variable [NormedAddCommGroup M] [InnerProductSpace ℂ M] [CompleteSpace M]
variable [FiniteDimensional ℂ M]

/-- The finite-dimensional active positive carrier generated by a selected screen. -/
abbrev ActiveCarrier (Y : M →L[ℂ] Kpos) : Type _ :=
  Y.range

/-- The selected screen corestricted to its active range. -/
noncomputable def activeScreen (Y : M →L[ℂ] Kpos) :
    M →L[ℂ] ActiveCarrier Y :=
  Y.rangeRestrict

/-- The map whose Gram operator acts on the active positive carrier. -/
noncomputable def activeAdjoint (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] M :=
  (activeScreen Y)†

/-- Corestriction to the active range preserves operator norm. -/
theorem wd_t11_norm_activeScreen
    (Y : M →L[ℂ] Kpos) :
    ‖activeScreen Y‖ = ‖Y‖ := by
  apply le_antisymm
  · apply ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg Y)
    intro x
    change ‖Y x‖ ≤ ‖Y‖ * ‖x‖
    exact ContinuousLinearMap.le_opNorm Y x
  · apply ContinuousLinearMap.opNorm_le_bound Y (norm_nonneg (activeScreen Y))
    intro x
    have h := ContinuousLinearMap.le_opNorm (activeScreen Y) x
    simpa [activeScreen] using h

/-- The adjoint active map has the same norm as the original selected screen. -/
theorem wd_t11_norm_activeAdjoint
    (Y : M →L[ℂ] Kpos) :
    ‖activeAdjoint Y‖ = ‖Y‖ := by
  rw [activeAdjoint, ContinuousLinearMap.adjoint.norm_map,
    wd_t11_norm_activeScreen]


/-- Active covariance on the finite-dimensional positive carrier. -/
noncomputable def activeCovariance (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] ActiveCarrier Y :=
  (activeAdjoint Y)† ∘L activeAdjoint Y

/-- The graph form on the active positive carrier. -/
noncomputable def activeGraphQ (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y) : ℝ :=
  ‖a‖ ^ 2 - ‖activeAdjoint Y a‖ ^ 2

/--
Fixed finite-sector criticality is attained: if the selected screening map has
operator norm one, the active graph form has an actual nonzero neutral vector.
-/
theorem wd_t11_norm_one_attains_neutral
    (Y : M →L[ℂ] Kpos)
    (hY : ‖Y‖ = 1) :
    ∃ a : ActiveCarrier Y, a ≠ 0 ∧ activeGraphQ Y a = 0 := by
  let W := activeAdjoint Y
  have hWnorm : ‖W‖ = 1 := by
    simpa [W] using (wd_t11_norm_activeAdjoint Y).trans hY
  have hWne : W ≠ 0 := by
    intro hzero
    rw [hzero, norm_zero] at hWnorm
    norm_num at hWnorm
  have hnotSub : ¬ Subsingleton (ActiveCarrier Y) := by
    intro hsub
    apply hWne
    apply ContinuousLinearMap.ext
    intro x
    have hx : x = 0 := Subsingleton.elim x 0
    simp [hx]
  letI : Nontrivial (ActiveCarrier Y) :=
    not_subsingleton_iff_nontrivial.mp hnotSub
  letI : ProperSpace (ActiveCarrier Y) :=
    FiniteDimensional.proper_rclike ℂ (ActiveCarrier Y)
  obtain ⟨x : ActiveCarrier Y, hx⟩ := exists_ne (0 : ActiveCarrier Y)
  let u : ActiveCarrier Y := (‖x‖⁻¹ : ℂ) • x
  have hu : ‖u‖ = 1 := by
    simp [u, norm_smul_inv_norm hx]
  have hsphere : (Metric.sphere (0 : ActiveCarrier Y) 1).Nonempty := by
    refine ⟨u, ?_⟩
    simpa [Metric.mem_sphere] using hu
  obtain ⟨a, haS, haMax⟩ :=
    (isCompact_sphere (0 : ActiveCarrier Y) 1).exists_isMaxOn
      hsphere W.continuous.norm.continuousOn
  have haNorm : ‖a‖ = 1 := by
    simpa [Metric.mem_sphere] using haS
  have hupper : ‖W‖ ≤ ‖W a‖ := by
    apply W.opNorm_le_bound' (norm_nonneg (W a))
    intro z hz
    apply haMax
    simpa [Metric.mem_sphere] using hz
  have hlower : ‖W a‖ ≤ ‖W‖ := by
    have h := W.le_opNorm a
    simpa [haNorm] using h
  have hWa : ‖W a‖ = 1 := by
    have : ‖W a‖ = ‖W‖ := le_antisymm hlower hupper
    rw [this, hWnorm]
  refine ⟨a, ?_, ?_⟩
  · intro ha0
    rw [ha0, norm_zero] at haNorm
    norm_num at haNorm
  · unfold activeGraphQ
    change ‖a‖ ^ 2 - ‖W a‖ ^ 2 = 0
    rw [haNorm, hWa]
    norm_num

/-- Sorted eigenbasis of the active covariance. -/
noncomputable def activeEigenbasis (Y : M →L[ℂ] Kpos) :
    OrthonormalBasis (Fin (finrank ℂ (ActiveCarrier Y))) ℂ (ActiveCarrier Y) :=
  (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis rfl

/-- Singular values on the active carrier. These are the positive singular values of Y;
zero padding in the original finite selected sector does not affect the >1 or =1 counts. -/
noncomputable def activeSigma (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) : ℝ :=
  (activeAdjoint Y).toLinearMap.singularValues i

/-- Active covariance eigenvalues are the squares of the active singular values. -/
theorem wd_t11_sigma_sq_eq_eigenvalue
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i ^ 2
      =
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
  exact (activeAdjoint Y).toLinearMap.sq_singularValues_fin rfl i

/-- The active graph form on each spectral basis vector is 1 - sigma^2. -/
theorem wd_t11_graphQ_eigenvector
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeGraphQ Y (activeEigenbasis Y i)
      = 1 - activeSigma Y i ^ 2 := by
  let W := activeAdjoint Y
  let A := W† ∘L W
  let b :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
  have hb : ‖b i‖ = 1 := OrthonormalBasis.norm_eq_one b i
  have hAw :
      A (b i)
        =
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) • b i := by
    exact W.toLinearMap.isSymmetric_adjoint_comp_self.apply_eigenvectorBasis rfl i
  have hgram :
      ‖W (b i)‖ ^ 2
        =
      W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
    have hinner :
        inner ℂ (A (b i)) (b i)
          =
        inner ℂ (W (b i)) (W (b i)) := by
      unfold A
      simp only [ContinuousLinearMap.comp_apply]
      exact ContinuousLinearMap.adjoint_inner_left W (b i) (W (b i))
    rw [hAw] at hinner
    simp [hb, inner_self_eq_norm_sq_to_K] at hinner
    exact_mod_cast hinner.symm
  change ‖b i‖ ^ 2 - ‖W (b i)‖ ^ 2 = _
  rw [hb, one_pow, hgram, wd_t11_sigma_sq_eq_eigenvalue Y i]

/-- A singular value is critical exactly when its Gram eigenvalue is one. -/
theorem wd_t11_sigma_eq_one_iff_eigenvalue_eq_one
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i = 1
      ↔
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i = 1 := by
  have hs := wd_t11_sigma_sq_eq_eigenvalue Y i
  have hnonneg : 0 ≤ activeSigma Y i := by
    exact (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  constructor
  · intro h
    rw [h] at hs
    norm_num at hs
    exact hs.symm
  · intro h
    rw [h] at hs
    nlinarith

/--
The active graph form is diagonal in the covariance eigenbasis, with one
weight 1 - sigma_i^2 per active singular direction.
-/
theorem wd_t11_graphQ_diagonal
    (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y) :
    activeGraphQ Y a
      =
    ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
      (1 - activeSigma Y i ^ 2) *
        ‖(activeEigenbasis Y).repr a i‖ ^ 2 := by
  let W := activeAdjoint Y
  let A := W† ∘L W
  let b := activeEigenbasis Y
  have hnormA :
      ‖a‖ ^ 2 =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          ‖b.repr a i‖ ^ 2 := by
    calc
      ‖a‖ ^ 2 = ‖b.repr a‖ ^ 2 := by
        rw [b.repr.norm_map]
      _ = ∑ i, ‖b.repr a i‖ ^ 2 :=
        EuclideanSpace.norm_sq_eq (b.repr a)
  have hinner :
      inner ℂ (A a) a = inner ℂ (W a) (W a) := by
    unfold A
    simp only [ContinuousLinearMap.comp_apply]
    exact ContinuousLinearMap.adjoint_inner_left W a (W a)
  have hdiag :
      inner ℂ (A a) a
        =
      ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
        (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
          ((‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
    calc
      inner ℂ (A a) a
          = inner ℂ (b.repr (A a)) (b.repr a) := by
              symm
              exact b.repr.inner_map_map (A a) a
      _ = ∑ i,
          inner ℂ ((b.repr (A a)) i) ((b.repr a) i) := by
              exact PiLp.inner_apply (b.repr (A a)) (b.repr a)
      _ = ∑ i,
          (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
            ((‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
              apply Finset.sum_congr rfl
              intro i _
              have hcoord :=
                W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis_apply_self_apply
                  (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
                  a i
              change
                inner ℂ ((b.repr (A a)) i) ((b.repr a) i)
                  =
                _
              change
                (b.repr (A a)) i
                  =
                _ at hcoord
              rw [hcoord]
              simp [RCLike.inner_apply, Complex.normSq_eq_abs]
  have hnormW :
      ‖W a‖ ^ 2 =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          activeSigma Y i ^ 2 * ‖b.repr a i‖ ^ 2 := by
    have hc :
        (((‖W a‖ ^ 2 : ℝ) : ℂ))
          =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          (((activeSigma Y i ^ 2 * ‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
      rw [← inner_self_eq_norm_sq_to_K]
      rw [← hinner, hdiag]
      apply Finset.sum_congr rfl
      intro i _
      rw [wd_t11_sigma_sq_eq_eigenvalue Y i]
      norm_cast
    exact_mod_cast hc
  unfold activeGraphQ
  rw [hnormA, hnormW]
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- Spectral indices carrying negative graph directions. -/
noncomputable def negativeIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => 1 < activeSigma Y i)

/-- Spectral indices carrying neutral graph directions. -/
noncomputable def neutralIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => activeSigma Y i = 1)

/-- The finite negative spectral space. -/
noncomputable def negativeSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Submodule.span ℂ
    (Set.range (fun i : {i // i ∈ negativeIndices Y} =>
      activeEigenbasis Y i.1))

/-- The negative spectral space has exactly one complex dimension per singular value > 1. -/
theorem wd_t11_negative_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (negativeSpectralSpace Y)
      = (negativeIndices Y).card := by
  unfold negativeSpectralSpace
  rw [finrank_span_eq_card]
  · exact Fintype.card_coe _
  · exact (activeEigenbasis Y).toBasis.linearIndependent.comp
      (fun i : {i // i ∈ negativeIndices Y} => i.1)
      Subtype.val_injective

/-- The neutral space is the eigenspace of the active covariance at eigenvalue one. -/
noncomputable def neutralSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ)

/-- Neutral spectral multiplicity equals the number of active singular values equal to one. -/
theorem wd_t11_neutral_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (neutralSpectralSpace Y)
      = (neutralIndices Y).card := by
  let W := activeAdjoint Y
  have hcard :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.card_filter_eigenvalues_eq
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
      (1 : ℂ)
  have hfilter :
      ({i |
        W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i
          = (1 : ℂ)} :
        Finset (Fin (finrank ℂ (ActiveCarrier Y))))
      =
      neutralIndices Y := by
    ext i
    simp only [Finset.mem_filter, Finset.mem_univ, true_and,
      neutralIndices]
    change
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℂ)
          = (1 : ℂ))
        ↔ activeSigma Y i = 1
    constructor
    · intro heig
      apply (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).2
      exact_mod_cast heig
    · intro hsigma
      have hreal :=
        (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).1 hsigma
      exact_mod_cast hreal
  change
    finrank ℂ
      (Module.End.eigenspace
        (((W†) ∘L W).toLinearMap) (1 : ℂ))
      =
    (neutralIndices Y).card
  rw [← hfilter]
  exact hcard.symm

/-- Every vector in the neutral spectral space is genuinely neutral for the graph form. -/
theorem wd_t11_neutral_space_graphQ_zero
    (Y : M →L[ℂ] Kpos)
    (a : neutralSpectralSpace Y) :
    activeGraphQ Y (a : ActiveCarrier Y) = 0 := by
  let W := activeAdjoint Y
  have ha :
      ((W†) ∘L W) (a : ActiveCarrier Y) = (a : ActiveCarrier Y) := by
    have hmem :
        (a : ActiveCarrier Y) ∈
          Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ) := by
      simpa [neutralSpectralSpace] using a.property
    rw [Module.End.mem_eigenspace_iff] at hmem
    simpa [activeCovariance, W] using hmem
  have hinner :
      inner ℂ (((W†) ∘L W) (a : ActiveCarrier Y)) (a : ActiveCarrier Y)
        =
      inner ℂ (W (a : ActiveCarrier Y)) (W (a : ActiveCarrier Y)) := by
    simp only [ContinuousLinearMap.comp_apply]
    exact ContinuousLinearMap.adjoint_inner_left
      W (a : ActiveCarrier Y) (W (a : ActiveCarrier Y))
  rw [ha] at hinner
  unfold activeGraphQ
  change ‖(a : ActiveCarrier Y)‖ ^ 2 -
    ‖W (a : ActiveCarrier Y)‖ ^ 2 = 0
  have hnormc :
      ((‖(a : ActiveCarrier Y)‖ : ℂ) ^ 2)
        =
      ((‖W (a : ActiveCarrier Y)‖ : ℂ) ^ 2) := by
    simpa only [inner_self_eq_norm_sq_to_K] using hinner
  have hnorm :
      ‖(a : ActiveCarrier Y)‖ ^ 2
        = ‖W (a : ActiveCarrier Y)‖ ^ 2 := by
    exact_mod_cast hnormc
  exact sub_eq_zero.mpr hnorm

/-- Each sigma > 1 basis direction is strictly negative. -/
theorem wd_t11_negative_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ negativeIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) < 0 := by
  rw [wd_t11_graphQ_eigenvector]
  simp only [negativeIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
  have hnonneg := (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  nlinarith

/-- Each sigma = 1 basis direction is an actual nonzero neutral vector. -/
theorem wd_t11_neutral_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ neutralIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) = 0
      ∧ activeEigenbasis Y i ≠ 0 := by
  constructor
  · rw [wd_t11_graphQ_eigenvector]
    simp only [neutralIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
    rw [hi]
    norm_num
  · exact (activeEigenbasis Y).toBasis.ne_zero i

/--
WD-T11 finite-sector spectral inertia package on the canonical active carrier:
negative and neutral multiplicities are counted by sigma > 1 and sigma = 1,
and every critical sigma = 1 produces an attained nonzero neutral graph vector.
-/
theorem wd_t11_finite_sector_singular_value_inertia
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (negativeSpectralSpace Y) = (negativeIndices Y).card
    ∧
    finrank ℂ (neutralSpectralSpace Y) = (neutralIndices Y).card
    ∧
    (∀ i, i ∈ negativeIndices Y →
      activeGraphQ Y (activeEigenbasis Y i) < 0)
    ∧
    (∀ i, i ∈ neutralIndices Y →
      activeGraphQ Y (activeEigenbasis Y i) = 0
        ∧ activeEigenbasis Y i ≠ 0) := by
  exact ⟨
    wd_t11_negative_space_finrank Y,
    wd_t11_neutral_space_finrank Y,
    wd_t11_negative_basis_direction Y,
    wd_t11_neutral_basis_direction Y
  ⟩

end WeilDefect.WDT11
