import WeilDefect.Screening.GraphNormalForm
import Mathlib.Analysis.InnerProductSpace.SingularValues
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.Normed.Module.Bases
import Mathlib

namespace WeilDefect.WDT11

open scoped InnerProduct
open ContinuousLinearMap
open InnerProductSpace
open Module
open WeilDefect.WDT01
open WeilDefect.WDT03

variable {Kpos M : Type*}
variable [NormedAddCommGroup Kpos] [InnerProductSpace ℂ Kpos] [CompleteSpace Kpos]
variable [NormedAddCommGroup M] [InnerProductSpace ℂ M] [CompleteSpace M]
variable [FiniteDimensional ℂ M]

/-- The finite-dimensional active positive carrier generated by a selected screen. -/
abbrev ActiveCarrier (Y : M →L[ℂ] Kpos) : Type _ :=
  Y.range

/-- The selected screen corestricted to its active range. -/
noncomputable def activeScreen (Y : M →L[ℂ] Kpos) :
    M →L[ℂ] ActiveCarrier Y :=
  Y.rangeRestrict

/-- The map whose Gram operator acts on the active positive carrier. -/
noncomputable def activeAdjoint (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] M :=
  (activeScreen Y)†

/-- Active covariance on the finite-dimensional positive carrier. -/
noncomputable def activeCovariance (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] ActiveCarrier Y :=
  (activeAdjoint Y)† ∘L activeAdjoint Y

/-- The graph form on the active positive carrier. -/
noncomputable def activeGraphQ (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y) : ℝ :=
  ‖a‖ ^ 2 - ‖activeAdjoint Y a‖ ^ 2

/-- Sorted eigenbasis of the active covariance. -/
noncomputable def activeEigenbasis (Y : M →L[ℂ] Kpos) :
    OrthonormalBasis (Fin (finrank ℂ (ActiveCarrier Y))) ℂ (ActiveCarrier Y) :=
  (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis rfl

/-- Singular values on the active carrier. These are the positive singular values of Y;
zero padding in the original finite selected sector does not affect the >1 or =1 counts. -/
noncomputable def activeSigma (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) : ℝ :=
  (activeAdjoint Y).toLinearMap.singularValues i

/-- Active covariance eigenvalues are the squares of the active singular values. -/
theorem wd_t11_sigma_sq_eq_eigenvalue
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i ^ 2
      =
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
  exact (activeAdjoint Y).toLinearMap.sq_singularValues_fin rfl i

/-- The active graph form on each spectral basis vector is 1 - sigma^2. -/
theorem wd_t11_graphQ_eigenvector
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeGraphQ Y (activeEigenbasis Y i)
      = 1 - activeSigma Y i ^ 2 := by
  let W := activeAdjoint Y
  let A := W† ∘L W
  let b :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
  have hb : ‖b i‖ = 1 := OrthonormalBasis.norm_eq_one b i
  have hAw :
      A (b i)
        =
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) • b i := by
    exact W.toLinearMap.isSymmetric_adjoint_comp_self.apply_eigenvectorBasis rfl i
  have hgram :
      ‖W (b i)‖ ^ 2
        =
      W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
    have hinner :
        inner ℂ (A (b i)) (b i)
          =
        inner ℂ (W (b i)) (W (b i)) := by
      unfold A
      simp only [ContinuousLinearMap.comp_apply]
      exact ContinuousLinearMap.adjoint_inner_left W (b i) (W (b i))
    rw [hAw] at hinner
    simp [hb, inner_self_eq_norm_sq_to_K] at hinner
    exact_mod_cast hinner.symm
  change ‖b i‖ ^ 2 - ‖W (b i)‖ ^ 2 = _
  rw [hb, one_pow, hgram, wd_t11_sigma_sq_eq_eigenvalue Y i]

/-- A singular value is critical exactly when its Gram eigenvalue is one. -/
theorem wd_t11_sigma_eq_one_iff_eigenvalue_eq_one
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i = 1
      ↔
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i = 1 := by
  have hs := wd_t11_sigma_sq_eq_eigenvalue Y i
  have hnonneg := (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  constructor
  · intro h
    rw [h] at hs
    norm_num at hs
    exact hs.symm
  · intro h
    rw [h] at hs
    nlinarith

/-- Spectral indices carrying negative graph directions. -/
noncomputable def negativeIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => 1 < activeSigma Y i)

/-- Spectral indices carrying neutral graph directions. -/
noncomputable def neutralIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => activeSigma Y i = 1)

/-- The finite negative spectral space. -/
noncomputable def negativeSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Submodule.span ℂ
    (Set.range (fun i : {i // i ∈ negativeIndices Y} =>
      activeEigenbasis Y i.1))

/-- The negative spectral space has exactly one complex dimension per singular value > 1. -/
theorem wd_t11_negative_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (negativeSpectralSpace Y)
      = (negativeIndices Y).card := by
  unfold negativeSpectralSpace
  rw [finrank_span_eq_card]
  · exact Fintype.card_coe _
  · exact (activeEigenbasis Y).toBasis.linearIndependent.comp
      (fun i : {i // i ∈ negativeIndices Y} => i.1)
      Subtype.val_injective

/-- The neutral space is the eigenspace of the active covariance at eigenvalue one. -/
noncomputable def neutralSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ)

/-- Neutral spectral multiplicity equals the number of active singular values equal to one. -/
theorem wd_t11_neutral_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (neutralSpectralSpace Y)
      = (neutralIndices Y).card := by
  let W := activeAdjoint Y
  have hcard :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.card_filter_eigenvalues_eq
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
      (1 : ℂ)
  have hfilter :
      ({i |
        W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i
          = (1 : ℂ)} :
        Finset (Fin (finrank ℂ (ActiveCarrier Y))))
      =
      neutralIndices Y := by
    ext i
    change
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℂ)
          = (1 : ℂ))
        ↔ activeSigma Y i = 1
    constructor
    · intro heig
      apply (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).2
      exact_mod_cast heig
    · intro hsigma
      have hreal :=
        (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).1 hsigma
      exact_mod_cast hreal
  change
    finrank ℂ
      (Module.End.eigenspace
        (((W†) ∘L W).toLinearMap) (1 : ℂ))
      =
    (neutralIndices Y).card
  rw [← hfilter]
  exact hcard.symm

/-- Every vector in the neutral spectral space is genuinely neutral for the graph form. -/
theorem wd_t11_neutral_space_graphQ_zero
    (Y : M →L[ℂ] Kpos)
    (a : neutralSpectralSpace Y) :
    activeGraphQ Y (a : ActiveCarrier Y) = 0 := by
  let W := activeAdjoint Y
  have ha :
      ((W†) ∘L W) (a : ActiveCarrier Y) = (a : ActiveCarrier Y) := by
    have hmem :
        (a : ActiveCarrier Y) ∈
          Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ) := by
      simpa [neutralSpectralSpace] using a.property
    rw [Module.End.mem_eigenspace_iff] at hmem
    simpa [activeCovariance, W] using hmem
  have hinner :
      inner ℂ (((W†) ∘L W) (a : ActiveCarrier Y)) (a : ActiveCarrier Y)
        =
      inner ℂ (W (a : ActiveCarrier Y)) (W (a : ActiveCarrier Y)) := by
    simp only [ContinuousLinearMap.comp_apply]
    exact ContinuousLinearMap.adjoint_inner_left
      W (a : ActiveCarrier Y) (W (a : ActiveCarrier Y))
  rw [ha] at hinner
  unfold activeGraphQ
  change ‖(a : ActiveCarrier Y)‖ ^ 2 -
    ‖W (a : ActiveCarrier Y)‖ ^ 2 = 0
  have hnorm :
      ‖(a : ActiveCarrier Y)‖ ^ 2
        = ‖W (a : ActiveCarrier Y)‖ ^ 2 := by
    have hre := congrArg Complex.re hinner
    simpa [inner_self_eq_norm_sq_to_K] using hre
  exact sub_eq_zero.mpr hnorm

/-- Each sigma > 1 basis direction is strictly negative. -/
theorem wd_t11_negative_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ negativeIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) < 0 := by
  rw [wd_t11_graphQ_eigenvector]
  simp only [negativeIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
  have hnonneg := (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  nlinarith

/-- Each sigma = 1 basis direction is an actual nonzero neutral vector. -/
theorem wd_t11_neutral_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ neutralIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) = 0
      ∧ activeEigenbasis Y i ≠ 0 := by
  constructor
  · rw [wd_t11_graphQ_eigenvector]
    simp only [neutralIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
    rw [hi]
    norm_num
  · exact (activeEigenbasis Y).toBasis.ne_zero i

/--
WD-T11 finite-sector spectral inertia package on the canonical active carrier:
negative and neutral multiplicities are counted by sigma > 1 and sigma = 1,
and every critical sigma = 1 produces an attained nonzero neutral graph vector.
-/
theorem wd_t11_finite_sector_singular_value_inertia
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (negativeSpectralSpace Y) = (negativeIndices Y).card
    ∧
    finrank ℂ (neutralSpectralSpace Y) = (neutralIndices Y).card
    ∧
    (∀ i, i ∈ negativeIndices Y →
      activeGraphQ Y (activeEigenbasis Y i) < 0)
    ∧
    (∀ i, i ∈ neutralIndices Y →
      activeGraphQ Y (activeEigenbasis Y i) = 0
        ∧ activeEigenbasis Y i ≠ 0) := by
  exact ⟨
    wd_t11_negative_space_finrank Y,
    wd_t11_neutral_space_finrank Y,
    wd_t11_negative_basis_direction Y,
    wd_t11_neutral_basis_direction Y
  ⟩

end WeilDefect.WDT11
