import WeilDefect.Screening.GraphNormalForm
import Mathlib.Analysis.InnerProductSpace.SingularValues
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.Normed.Module.Bases
import Mathlib

namespace WeilDefect.WDT11

open scoped InnerProduct
open ContinuousLinearMap
open InnerProductSpace
open Module
open WeilDefect.WDT01
open WeilDefect.WDT03

variable {Kpos M : Type*}
variable [NormedAddCommGroup Kpos] [InnerProductSpace ℂ Kpos] [CompleteSpace Kpos]
variable [NormedAddCommGroup M] [InnerProductSpace ℂ M] [CompleteSpace M]
variable [FiniteDimensional ℂ M]

/-- The finite-dimensional active positive carrier generated by a selected screen. -/
abbrev ActiveCarrier (Y : M →L[ℂ] Kpos) : Type _ :=
  Y.range

/-- The selected screen corestricted to its active range. -/
noncomputable def activeScreen (Y : M →L[ℂ] Kpos) :
    M →L[ℂ] ActiveCarrier Y :=
  Y.rangeRestrict

/-- The map whose Gram operator acts on the active positive carrier. -/
noncomputable def activeAdjoint (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] M :=
  (activeScreen Y)†

/-- Corestriction to the active range preserves operator norm. -/
theorem wd_t11_norm_activeScreen
    (Y : M →L[ℂ] Kpos) :
    ‖activeScreen Y‖ = ‖Y‖ := by
  apply le_antisymm
  · apply ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg Y)
    intro x
    change ‖Y x‖ ≤ ‖Y‖ * ‖x‖
    exact ContinuousLinearMap.le_opNorm Y x
  · apply ContinuousLinearMap.opNorm_le_bound Y (norm_nonneg (activeScreen Y))
    intro x
    have h := ContinuousLinearMap.le_opNorm (activeScreen Y) x
    change ‖((activeScreen Y x : ActiveCarrier Y) : Kpos)‖
      ≤ ‖activeScreen Y‖ * ‖x‖ at h
    change ‖Y x‖ ≤ ‖activeScreen Y‖ * ‖x‖
    exact h

/-- The adjoint active map has the same norm as the original selected screen. -/
theorem wd_t11_norm_activeAdjoint
    (Y : M →L[ℂ] Kpos) :
    ‖activeAdjoint Y‖ = ‖Y‖ := by
  rw [activeAdjoint, ContinuousLinearMap.adjoint.norm_map,
    wd_t11_norm_activeScreen]


/-- Active covariance on the finite-dimensional positive carrier. -/
noncomputable def activeCovariance (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] ActiveCarrier Y :=
  (activeAdjoint Y)† ∘L activeAdjoint Y

/-- The graph form on the active positive carrier. -/
noncomputable def activeGraphQ (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y) : ℝ :=
  ‖a‖ ^ 2 - ‖activeAdjoint Y a‖ ^ 2

/--
Fixed finite-sector criticality is attained: if the selected screening map has
operator norm one, the active graph form has an actual nonzero neutral vector.
-/
theorem wd_t11_norm_one_attains_neutral
    (Y : M →L[ℂ] Kpos)
    (hY : ‖Y‖ = 1) :
    ∃ a : ActiveCarrier Y, a ≠ 0 ∧ activeGraphQ Y a = 0 := by
  let W := activeAdjoint Y
  have hWnorm : ‖W‖ = 1 := by
    simpa [W] using (wd_t11_norm_activeAdjoint Y).trans hY
  have hWne : W ≠ 0 := by
    intro hzero
    rw [hzero] at hWnorm
    have hzeroNorm :
        ‖(0 : ActiveCarrier Y →L[ℂ] M)‖ = 0 :=
      ContinuousLinearMap.opNorm_zero
    have hfalse : (0 : ℝ) = 1 :=
      hzeroNorm.symm.trans hWnorm
    exact zero_ne_one hfalse
  have hnotSub : ¬ Subsingleton (ActiveCarrier Y) := by
    intro hsub
    apply hWne
    apply ContinuousLinearMap.ext
    intro x
    have hx : x = 0 := Subsingleton.elim x 0
    simp [hx]
  letI : Nontrivial (ActiveCarrier Y) :=
    not_subsingleton_iff_nontrivial.mp hnotSub
  letI : ProperSpace (ActiveCarrier Y) :=
    FiniteDimensional.proper_rclike ℂ (ActiveCarrier Y)
  obtain ⟨x : ActiveCarrier Y, hx⟩ := exists_ne (0 : ActiveCarrier Y)
  let u : ActiveCarrier Y := (‖x‖⁻¹ : ℂ) • x
  have hu : ‖u‖ = 1 := by
    simpa [u] using (norm_smul_inv_norm (𝕜 := ℂ) hx)
  have hsphere : (Metric.sphere (0 : ActiveCarrier Y) 1).Nonempty := by
    refine ⟨u, ?_⟩
    simpa [Metric.mem_sphere] using hu
  obtain ⟨a, haS, haMax⟩ :=
    (isCompact_sphere (0 : ActiveCarrier Y) 1).exists_isMaxOn
      hsphere W.continuous.norm.continuousOn
  have haNorm : ‖a‖ = 1 := by
    simpa [Metric.mem_sphere] using haS
  have hupper : ‖W‖ ≤ ‖W a‖ := by
    apply ContinuousLinearMap.opNorm_le_of_unit_norm (norm_nonneg (W a))
    intro z hz
    apply haMax
    simpa [Metric.mem_sphere] using hz
  have hlower : ‖W a‖ ≤ ‖W‖ := by
    have h := W.le_opNorm a
    simpa [haNorm] using h
  have hWa : ‖W a‖ = 1 := by
    have : ‖W a‖ = ‖W‖ := le_antisymm hlower hupper
    rw [this, hWnorm]
  refine ⟨a, ?_, ?_⟩
  · intro ha0
    rw [ha0, norm_zero] at haNorm
    norm_num at haNorm
  · unfold activeGraphQ
    change ‖a‖ ^ 2 - ‖W a‖ ^ 2 = 0
    rw [haNorm, hWa]
    norm_num

/-- Sorted eigenbasis of the active covariance. -/
noncomputable def activeEigenbasis (Y : M →L[ℂ] Kpos) :
    OrthonormalBasis (Fin (finrank ℂ (ActiveCarrier Y))) ℂ (ActiveCarrier Y) :=
  (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis rfl

/-- Singular values on the active carrier. These are the positive singular values of Y;
zero padding in the original finite selected sector does not affect the >1 or =1 counts. -/
noncomputable def activeSigma (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) : ℝ :=
  (activeAdjoint Y).toLinearMap.singularValues i

/-- Active covariance eigenvalues are the squares of the active singular values. -/
theorem wd_t11_sigma_sq_eq_eigenvalue
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i ^ 2
      =
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
  exact (activeAdjoint Y).toLinearMap.sq_singularValues_fin rfl i

/-- The active graph form on each spectral basis vector is 1 - sigma^2. -/
theorem wd_t11_graphQ_eigenvector
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeGraphQ Y (activeEigenbasis Y i)
      = 1 - activeSigma Y i ^ 2 := by
  let W := activeAdjoint Y
  let A := W† ∘L W
  let b :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
  have hb : ‖b i‖ = 1 := OrthonormalBasis.norm_eq_one b i
  have hAw :
      A (b i)
        =
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) • b i := by
    exact W.toLinearMap.isSymmetric_adjoint_comp_self.apply_eigenvectorBasis rfl i
  have hgram :
      ‖W (b i)‖ ^ 2
        =
      W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i := by
    have hinner :
        inner ℂ (A (b i)) (b i)
          =
        inner ℂ (W (b i)) (W (b i)) := by
      unfold A
      simp only [ContinuousLinearMap.comp_apply]
      exact ContinuousLinearMap.adjoint_inner_left W (b i) (W (b i))
    rw [hAw] at hinner
    simp [hb, inner_self_eq_norm_sq_to_K] at hinner
    exact_mod_cast hinner.symm
  change ‖b i‖ ^ 2 - ‖W (b i)‖ ^ 2 = _
  rw [hb, one_pow, hgram, wd_t11_sigma_sq_eq_eigenvalue Y i]

/-- A singular value is critical exactly when its Gram eigenvalue is one. -/
theorem wd_t11_sigma_eq_one_iff_eigenvalue_eq_one
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y))) :
    activeSigma Y i = 1
      ↔
    (activeAdjoint Y).toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i = 1 := by
  have hs := wd_t11_sigma_sq_eq_eigenvalue Y i
  have hnonneg : 0 ≤ activeSigma Y i := by
    exact (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  constructor
  · intro h
    rw [h] at hs
    norm_num at hs
    exact hs.symm
  · intro h
    rw [h] at hs
    nlinarith

/--
The active graph form is diagonal in the covariance eigenbasis, with one
weight 1 - sigma_i^2 per active singular direction.
-/
theorem wd_t11_graphQ_diagonal
    (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y) :
    activeGraphQ Y a
      =
    ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
      (1 - activeSigma Y i ^ 2) *
        ‖(activeEigenbasis Y).repr a i‖ ^ 2 := by
  let W := activeAdjoint Y
  let A := W† ∘L W
  let b := activeEigenbasis Y
  have hnormA :
      ‖a‖ ^ 2 =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          ‖b.repr a i‖ ^ 2 := by
    calc
      ‖a‖ ^ 2 = ‖b.repr a‖ ^ 2 := by
        rw [b.repr.norm_map]
      _ = ∑ i, ‖b.repr a i‖ ^ 2 :=
        EuclideanSpace.norm_sq_eq (b.repr a)
  have hinner :
      inner ℂ (A a) a = inner ℂ (W a) (W a) := by
    unfold A
    simp only [ContinuousLinearMap.comp_apply]
    exact ContinuousLinearMap.adjoint_inner_left W a (W a)
  have hdiag :
      inner ℂ (A a) a
        =
      ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
        (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
          ((‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
    calc
      inner ℂ (A a) a
          = inner ℂ (b.repr (A a)) (b.repr a) := by
              symm
              exact b.repr.inner_map_map (A a) a
      _ = ∑ i,
          inner ℂ ((b.repr (A a)) i) ((b.repr a) i) := by
              exact PiLp.inner_apply (b.repr (A a)) (b.repr a)
      _ = ∑ i,
          (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
            ((‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
              apply Finset.sum_congr rfl
              intro i _
              have hcoord :=
                W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvectorBasis_apply_self_apply
                  (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
                  a i
              change
                inner ℂ ((b.repr (A a)) i) ((b.repr a) i)
                  =
                _
              change
                (b.repr (A a)) i
                  =
                _ at hcoord
              rw [hcoord]
              simp only [RCLike.inner_apply, map_mul, RCLike.star_def,
                RCLike.conj_ofReal]
              change
                (b.repr a i) *
                    (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
                      (starRingEnd ℂ) (b.repr a i))
                  =
                (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
                  (((‖b.repr a i‖ ^ 2 : ℝ) : ℂ)))
              calc
                _ =
                    (((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℝ) : ℂ) *
                      ((b.repr a i) * (starRingEnd ℂ) (b.repr a i))) := by
                        ring
                _ = _ := by
                  rw [RCLike.mul_conj]
                  push_cast
                  rfl
  have hnormW :
      ‖W a‖ ^ 2 =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          activeSigma Y i ^ 2 * ‖b.repr a i‖ ^ 2 := by
    have hc :
        inner ℂ (W a) (W a)
          =
        ∑ i : Fin (finrank ℂ (ActiveCarrier Y)),
          (((activeSigma Y i ^ 2 * ‖b.repr a i‖ ^ 2 : ℝ) : ℂ)) := by
      rw [← hinner, hdiag]
      apply Finset.sum_congr rfl
      intro i _
      rw [wd_t11_sigma_sq_eq_eigenvalue Y i]
      norm_cast
    have hc' := hc
    simp only [inner_self_eq_norm_sq_to_K] at hc'
    refine Complex.ofReal_injective ?_
    push_cast
    push_cast at hc'
    exact hc'
  unfold activeGraphQ
  rw [hnormA, hnormW]
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- Spectral indices carrying negative graph directions. -/
noncomputable def negativeIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => 1 < activeSigma Y i)

/-- Spectral indices carrying neutral graph directions. -/
noncomputable def neutralIndices (Y : M →L[ℂ] Kpos) :
    Finset (Fin (finrank ℂ (ActiveCarrier Y))) :=
  Finset.univ.filter (fun i => activeSigma Y i = 1)

/-- Coordinates along the singular directions whose gain exceeds one. -/
noncomputable def negativeCoordinates (Y : M →L[ℂ] Kpos) :
    ActiveCarrier Y →L[ℂ] ({i // i ∈ negativeIndices Y} → ℂ) :=
  ContinuousLinearMap.pi fun i =>
    (EuclideanSpace.proj i.1).comp
      (activeEigenbasis Y).repr.toContinuousLinearEquiv.toContinuousLinearMap

/-- Vanishing of all negative spectral coordinates forces the graph form to be nonnegative. -/
theorem wd_t11_graphQ_nonneg_of_negativeCoordinates_zero
    (Y : M →L[ℂ] Kpos)
    (a : ActiveCarrier Y)
    (ha : negativeCoordinates Y a = 0) :
    0 ≤ activeGraphQ Y a := by
  rw [wd_t11_graphQ_diagonal]
  apply Finset.sum_nonneg
  intro i _
  by_cases hi : i ∈ negativeIndices Y
  · have hcoord := congrFun ha ⟨i, hi⟩
    have hz : (activeEigenbasis Y).repr a i = 0 := by
      simpa [negativeCoordinates] using hcoord
    simp [hz]
  · have hsle : activeSigma Y i ≤ 1 := by
      simp only [negativeIndices, Finset.mem_filter, Finset.mem_univ,
        true_and] at hi
      exact le_of_not_gt hi
    have hsnonneg : 0 ≤ activeSigma Y i :=
      (activeAdjoint Y).toLinearMap.singularValues_nonneg i
    have hweight : 0 ≤ 1 - activeSigma Y i ^ 2 := by
      nlinarith
    exact mul_nonneg hweight (sq_nonneg _)

/--
Any finite negative witness injects into the coordinates with singular value
strictly larger than one. Hence its rank cannot exceed their number.
-/
theorem wd_t11_negative_rank_le_count
    (Y : M →L[ℂ] Kpos)
    {n : ℕ}
    (hneg : HasNegativeRank (activeGraphQ Y) Set.univ n) :
    n ≤ (negativeIndices Y).card := by
  rcases hneg with ⟨T, _, hTneg⟩
  let C :
      EuclideanSpace ℂ (Fin n) →L[ℂ]
        ({i // i ∈ negativeIndices Y} → ℂ) :=
    (negativeCoordinates Y).comp T
  have hCinj : Function.Injective C := by
    intro x y hxy
    by_contra hne
    have hd : x - y ≠ 0 := sub_ne_zero.mpr hne
    let u : EuclideanSpace ℂ (Fin n) := (‖x - y‖⁻¹ : ℂ) • (x - y)
    have hu : ‖u‖ = 1 := by
      simpa [u] using (norm_smul_inv_norm (𝕜 := ℂ) hd)
    have hCdiff : C (x - y) = 0 := by
      rw [map_sub, hxy, sub_self]
    have hCu : C u = 0 := by
      simp [u, hCdiff]
    have hcoord : negativeCoordinates Y (T u) = 0 := by
      simpa [C, ContinuousLinearMap.comp_apply] using hCu
    have hnonneg :=
      wd_t11_graphQ_nonneg_of_negativeCoordinates_zero Y (T u) hcoord
    have hstrict := hTneg u hu
    linarith
  have hdim :=
    LinearMap.finrank_le_finrank_of_injective
      (f := C.toLinearMap) hCinj
  simpa [C, Fintype.card_coe] using hdim

/-- The finite negative spectral space. -/
noncomputable def negativeSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Submodule.span ℂ
    (Set.range (fun i : {i // i ∈ negativeIndices Y} =>
      activeEigenbasis Y i.1))

/-- Coordinates outside the negative spectral block vanish on its span. -/
theorem wd_t11_negative_space_coordinate_zero
    (Y : M →L[ℂ] Kpos)
    (a : negativeSpectralSpace Y)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∉ negativeIndices Y) :
    (activeEigenbasis Y).repr (a : ActiveCarrier Y) i = 0 := by
  rw [OrthonormalBasis.repr_apply_apply]
  have ha :
      (a : ActiveCarrier Y) ∈
        Submodule.span ℂ
          (Set.range (fun j : {j // j ∈ negativeIndices Y} =>
            activeEigenbasis Y j.1)) := by
    simpa [negativeSpectralSpace] using a.property
  refine Submodule.span_induction
    (p := fun (x : ActiveCarrier Y) _ =>
      inner ℂ (activeEigenbasis Y i) x = 0)
    ?_ ?_ ?_ ?_ ha
  · intro x hx
    obtain ⟨j, rfl⟩ := hx
    have hij : i ≠ j.1 := by
      intro h
      apply hi
      simpa [h] using j.2
    simpa [hij] using
      (orthonormal_iff_ite.mp (activeEigenbasis Y).orthonormal i j.1)
  · simp
  · intro x y hx hy hix hiy
    simp [inner_add_right, hix, hiy]
  · intro c x hx hix
    simp [inner_smul_right, hix]

/-- The whole negative spectral space, not just its basis rays, is strictly negative. -/
theorem wd_t11_negative_space_strict
    (Y : M →L[ℂ] Kpos)
    (a : negativeSpectralSpace Y)
    (ha : a ≠ 0) :
    activeGraphQ Y (a : ActiveCarrier Y) < 0 := by
  rw [wd_t11_graphQ_diagonal]
  let t : Fin (finrank ℂ (ActiveCarrier Y)) → ℝ :=
    fun i =>
      (1 - activeSigma Y i ^ 2) *
        ‖(activeEigenbasis Y).repr (a : ActiveCarrier Y) i‖ ^ 2
  have hle : ∀ i ∈ (Finset.univ :
      Finset (Fin (finrank ℂ (ActiveCarrier Y)))), t i ≤ 0 := by
    intro i _
    by_cases hi : i ∈ negativeIndices Y
    · have hsig : 1 < activeSigma Y i := by
        simpa [negativeIndices] using hi
      have hweight : 1 - activeSigma Y i ^ 2 < 0 := by
        nlinarith
      exact mul_nonpos_of_nonpos_of_nonneg hweight.le (sq_nonneg _)
    · have hz :=
        wd_t11_negative_space_coordinate_zero Y a i hi
      simp [t, hz]
  have ha0 : (a : ActiveCarrier Y) ≠ 0 := by
    intro h
    apply ha
    exact Subtype.ext h
  have hrepr :
      (activeEigenbasis Y).repr (a : ActiveCarrier Y) ≠ 0 := by
    intro h
    apply ha0
    apply (activeEigenbasis Y).repr.injective
    simpa using h
  have hex :
      ∃ i : Fin (finrank ℂ (ActiveCarrier Y)),
        (activeEigenbasis Y).repr (a : ActiveCarrier Y) i ≠ 0 := by
    by_contra h
    push_neg at h
    apply hrepr
    ext i
    exact h i
  obtain ⟨i, hiCoord⟩ := hex
  have hiNeg : i ∈ negativeIndices Y := by
    by_contra hi
    exact hiCoord (wd_t11_negative_space_coordinate_zero Y a i hi)
  have hsig : 1 < activeSigma Y i := by
    simpa [negativeIndices] using hiNeg
  have hweight : 1 - activeSigma Y i ^ 2 < 0 := by
    nlinarith
  have hcoordpos :
      0 < ‖(activeEigenbasis Y).repr (a : ActiveCarrier Y) i‖ ^ 2 := by
    positivity
  have hstrict : t i < 0 :=
    mul_neg_of_neg_of_pos hweight hcoordpos
  have hsum :
      (∑ j ∈ (Finset.univ :
          Finset (Fin (finrank ℂ (ActiveCarrier Y)))), t j)
        <
      ∑ _j ∈ (Finset.univ :
          Finset (Fin (finrank ℂ (ActiveCarrier Y)))), (0 : ℝ) := by
    refine Finset.sum_lt_sum ?_ ?_
    · intro j hj
      exact hle j hj
    · exact ⟨i, Finset.mem_univ _, hstrict⟩
  simpa [t] using hsum

/-- The negative spectral space has exactly one complex dimension per singular value > 1. -/
theorem wd_t11_negative_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (negativeSpectralSpace Y)
      = (negativeIndices Y).card := by
  unfold negativeSpectralSpace
  rw [finrank_span_eq_card]
  · exact Fintype.card_coe _
  · exact (activeEigenbasis Y).toBasis.linearIndependent.comp
      (fun i : {i // i ∈ negativeIndices Y} => i.1)
      Subtype.val_injective

/-- The full sigma > 1 count is itself realized by a negative witness. -/
theorem wd_t11_negative_rank_count_exists
    (Y : M →L[ℂ] Kpos) :
    HasNegativeRank
      (activeGraphQ Y)
      Set.univ
      (negativeIndices Y).card := by
  let E :
      EuclideanSpace ℂ (Fin (negativeIndices Y).card)
        ≃L[ℂ] negativeSpectralSpace Y :=
    ContinuousLinearEquiv.ofFinrankEq (by
      simpa [wd_t11_negative_space_finrank Y])
  let T :
      EuclideanSpace ℂ (Fin (negativeIndices Y).card)
        →L[ℂ] ActiveCarrier Y :=
    (negativeSpectralSpace Y).subtypeL.comp E.toContinuousLinearMap
  refine ⟨T, ?_, ?_⟩
  · intro x
    exact Set.mem_univ _
  · intro x hx
    have hxne : x ≠ 0 := by
      intro hx0
      rw [hx0, norm_zero] at hx
      norm_num at hx
    have hEne : E x ≠ 0 := by
      intro hEx
      apply hxne
      apply E.injective
      simpa using hEx
    simpa [T, ContinuousLinearMap.comp_apply] using
      wd_t11_negative_space_strict Y (E x) hEne

/--
The sigma > 1 count is the exact maximal finite negative rank: it is attained,
and every other finite negative witness has no larger rank.
-/
theorem wd_t11_negative_index_exact
    (Y : M →L[ℂ] Kpos) :
    HasNegativeRank
      (activeGraphQ Y)
      Set.univ
      (negativeIndices Y).card
    ∧
    ∀ n : ℕ,
      HasNegativeRank (activeGraphQ Y) Set.univ n →
        n ≤ (negativeIndices Y).card := by
  exact ⟨
    wd_t11_negative_rank_count_exists Y,
    fun _ h => wd_t11_negative_rank_le_count Y h
  ⟩

/-- The neutral space is the eigenspace of the active covariance at eigenvalue one. -/
noncomputable def neutralSpectralSpace (Y : M →L[ℂ] Kpos) :
    Submodule ℂ (ActiveCarrier Y) :=
  Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ)

/-- Neutral spectral multiplicity equals the number of active singular values equal to one. -/
theorem wd_t11_neutral_space_finrank
    (Y : M →L[ℂ] Kpos) :
    finrank ℂ (neutralSpectralSpace Y)
      = (neutralIndices Y).card := by
  let W := activeAdjoint Y
  have hcard :=
    W.toLinearMap.isSymmetric_adjoint_comp_self.card_filter_eigenvalues_eq
      (rfl : finrank ℂ (ActiveCarrier Y) = finrank ℂ (ActiveCarrier Y))
      (1 : ℂ)
  have hfilter :
      ({i |
        W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i
          = (1 : ℂ)} :
        Finset (Fin (finrank ℂ (ActiveCarrier Y))))
      =
      neutralIndices Y := by
    ext i
    simp only [Finset.mem_filter, Finset.mem_univ, true_and,
      neutralIndices]
    change
      ((W.toLinearMap.isSymmetric_adjoint_comp_self.eigenvalues rfl i : ℂ)
          = (1 : ℂ))
        ↔ activeSigma Y i = 1
    constructor
    · intro heig
      apply (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).2
      exact_mod_cast heig
    · intro hsigma
      have hreal :=
        (wd_t11_sigma_eq_one_iff_eigenvalue_eq_one Y i).1 hsigma
      exact_mod_cast hreal
  change
    finrank ℂ
      (Module.End.eigenspace
        (((W†) ∘L W).toLinearMap) (1 : ℂ))
      =
    (neutralIndices Y).card
  rw [← hfilter]
  exact hcard.symm

/-- Every vector in the neutral spectral space is genuinely neutral for the graph form. -/
theorem wd_t11_neutral_space_graphQ_zero
    (Y : M →L[ℂ] Kpos)
    (a : neutralSpectralSpace Y) :
    activeGraphQ Y (a : ActiveCarrier Y) = 0 := by
  let W := activeAdjoint Y
  have ha :
      ((W†) ∘L W) (a : ActiveCarrier Y) = (a : ActiveCarrier Y) := by
    have hmem :
        (a : ActiveCarrier Y) ∈
          Module.End.eigenspace (activeCovariance Y).toLinearMap (1 : ℂ) := by
      simpa [neutralSpectralSpace] using a.property
    rw [Module.End.mem_eigenspace_iff] at hmem
    simpa [activeCovariance, W] using hmem
  have hinner :
      inner ℂ (((W†) ∘L W) (a : ActiveCarrier Y)) (a : ActiveCarrier Y)
        =
      inner ℂ (W (a : ActiveCarrier Y)) (W (a : ActiveCarrier Y)) := by
    simp only [ContinuousLinearMap.comp_apply]
    exact ContinuousLinearMap.adjoint_inner_left
      W (a : ActiveCarrier Y) (W (a : ActiveCarrier Y))
  rw [ha] at hinner
  unfold activeGraphQ
  change ‖(a : ActiveCarrier Y)‖ ^ 2 -
    ‖W (a : ActiveCarrier Y)‖ ^ 2 = 0
  have hnorm :
      ‖(a : ActiveCarrier Y)‖ ^ 2
        = ‖W (a : ActiveCarrier Y)‖ ^ 2 := by
    have hinner' := hinner
    simp only [inner_self_eq_norm_sq_to_K] at hinner'
    exact_mod_cast hinner'
  exact sub_eq_zero.mpr hnorm

/-- Each sigma > 1 basis direction is strictly negative. -/
theorem wd_t11_negative_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ negativeIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) < 0 := by
  rw [wd_t11_graphQ_eigenvector]
  simp only [negativeIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
  have hnonneg := (activeAdjoint Y).toLinearMap.singularValues_nonneg i
  nlinarith

/-- Each sigma = 1 basis direction is an actual nonzero neutral vector. -/
theorem wd_t11_neutral_basis_direction
    (Y : M →L[ℂ] Kpos)
    (i : Fin (finrank ℂ (ActiveCarrier Y)))
    (hi : i ∈ neutralIndices Y) :
    activeGraphQ Y (activeEigenbasis Y i) = 0
      ∧ activeEigenbasis Y i ≠ 0 := by
  constructor
  · rw [wd_t11_graphQ_eigenvector]
    simp only [neutralIndices, Finset.mem_filter, Finset.mem_univ, true_and] at hi
    rw [hi]
    norm_num
  · exact (activeEigenbasis Y).toBasis.ne_zero i

/--
WD-T11 finite-sector singular-value inertia theorem on the canonical active
carrier.  The sigma > 1 count is the exact maximal finite negative rank, the
sigma = 1 count is the neutral dimension, and unit operator norm is necessarily
attained by an actual nonzero neutral graph direction.
-/
theorem wd_t11_finite_sector_singular_value_inertia
    (Y : M →L[ℂ] Kpos) :
    (HasNegativeRank
      (activeGraphQ Y)
      Set.univ
      (negativeIndices Y).card
      ∧
      ∀ n : ℕ,
        HasNegativeRank (activeGraphQ Y) Set.univ n →
          n ≤ (negativeIndices Y).card)
    ∧
    finrank ℂ (neutralSpectralSpace Y) = (neutralIndices Y).card
    ∧
    (‖Y‖ = 1 →
      ∃ a : ActiveCarrier Y,
        a ≠ 0 ∧ activeGraphQ Y a = 0) := by
  exact ⟨
    wd_t11_negative_index_exact Y,
    wd_t11_neutral_space_finrank Y,
    wd_t11_norm_one_attains_neutral Y
  ⟩

end WeilDefect.WDT11
