import WeilDefect.Arithmetic.LogarithmicForm
import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds

namespace WeilDefect

open Filter Asymptotics
open scoped Topology

/-- Positive-Sobolev squared frequency weight N^(2 eps). -/
noncomputable def positiveSobolevFrequencyWeight
    (eps x : ℝ) : ℝ :=
  x ^ (2 * eps)

/--
The canonical logarithmic Fourier weight is at most a constant multiple of
log x at high positive frequency.
-/
theorem logarithmicFourierWeight_isBigO_log :
    logarithmicFourierWeight =O[atTop] Real.log := by
  apply IsBigO.of_bound 2
  filter_upwards
    [eventually_ge_atTop (max (Real.exp 1) 2 : ℝ)] with x hx
  have hexp_le : Real.exp 1 ≤ x :=
    (le_max_left _ _).trans hx
  have htwo_le : (2 : ℝ) ≤ x :=
    (le_max_right _ _).trans hx
  have hxpos : 0 < x := lt_of_lt_of_le (by norm_num) htwo_le
  have hx0 : 0 ≤ x := hxpos.le
  have hargpos : 0 < Real.exp 1 + x := by positivity
  have hsum : Real.exp 1 + x ≤ x ^ 2 := by
    calc
      Real.exp 1 + x ≤ x + x := by
        simpa [add_comm] using add_le_add_right hexp_le x
      _ = 2 * x := by ring
      _ ≤ x ^ 2 := by nlinarith
  have hlog :
      Real.log (Real.exp 1 + x) ≤ 2 * Real.log x := by
    calc
      Real.log (Real.exp 1 + x)
          ≤ Real.log (x ^ 2) :=
        Real.log_le_log hargpos hsum
      _ = 2 * Real.log x := by
        rw [Real.log_pow]
        norm_num
  have hlogx : 0 ≤ Real.log x := Real.log_nonneg (by linarith)
  have hlogarg : 0 ≤ Real.log (Real.exp 1 + x) := by
    apply Real.log_nonneg
    have : (1 : ℝ) ≤ Real.exp 1 := by
      simpa using Real.one_le_exp 1
    linarith
  simpa [logarithmicFourierWeight, abs_of_nonneg hx0,
    abs_of_nonneg hlogarg, abs_of_nonneg hlogx] using hlog

/--
For every positive Sobolev exponent, logarithmic Fourier weight is little-o of
the squared Sobolev frequency weight.
-/
theorem logarithmicFourierWeight_isLittleO_positiveSobolev
    {eps : ℝ} (heps : 0 < eps) :
    logarithmicFourierWeight
      =o[atTop]
    fun x : ℝ => positiveSobolevFrequencyWeight eps x := by
  unfold positiveSobolevFrequencyWeight
  exact logarithmicFourierWeight_isBigO_log.trans_isLittleO
    (isLittleO_log_rpow_atTop (mul_pos (by norm_num) heps))

/--
The positive-Sobolev frequency weight cannot be uniformly O of the logarithmic
Fourier weight.
-/
theorem positiveSobolevFrequencyWeight_not_isBigO_logarithmic
    {eps : ℝ} (heps : 0 < eps) :
    ¬ (fun x : ℝ => positiveSobolevFrequencyWeight eps x)
        =O[atTop] logarithmicFourierWeight := by
  have hfreq :
      ∃ᶠ x : ℝ in atTop,
        logarithmicFourierWeight x ≠ 0 := by
    exact Frequently.of_forall fun x =>
      ne_of_gt
        (lt_of_lt_of_le zero_lt_one
          (one_le_logarithmicFourierWeight x))
  exact
    (logarithmicFourierWeight_isLittleO_positiveSobolev heps).not_isBigO
      hfreq

/--
WD-T36 transfer theorem.

Any fixed-support oscillatory witness family whose shifted Weil-form energy is
O(logarithmic weight), while its positive-Sobolev squared norm dominates
N^(2 eps), rules out a uniform coercive Sobolev estimate.
-/
theorem wd_t36_no_uniform_positive_sobolev_coercivity_of_witness
    {eps : ℝ} (heps : 0 < eps)
    (formSq sobolevSq : ℝ → ℝ)
    (hform :
      formSq =O[atTop] logarithmicFourierWeight)
    (hsob :
      (fun x : ℝ => positiveSobolevFrequencyWeight eps x)
        =O[atTop] sobolevSq) :
    ¬ sobolevSq =O[atTop] formSq := by
  intro hcoercive
  have hbad :
      (fun x : ℝ => positiveSobolevFrequencyWeight eps x)
        =O[atTop] logarithmicFourierWeight :=
    hsob.trans (hcoercive.trans hform)
  exact
    positiveSobolevFrequencyWeight_not_isBigO_logarithmic heps hbad

/--
WD-T36 / ZW2-T8 in its pure logarithmic-form sharpness model: no positive
Sobolev frequency weight can be uniformly controlled by the logarithmic form
weight at high frequency.
-/
theorem wd_t36_no_positive_sobolev_bootstrap
    {eps : ℝ} (heps : 0 < eps) :
    ¬ (fun x : ℝ => positiveSobolevFrequencyWeight eps x)
        =O[atTop] logarithmicFourierWeight :=
  positiveSobolevFrequencyWeight_not_isBigO_logarithmic heps


/-- Finite Fourier-side cosine correction generated by WD-T34 prime translations. -/
noncomputable def finitePrimeTrigCorrection
    (c : ℝ) (coeff : ℕ → ℝ) (t : ℝ) : ℝ :=
  Finset.sum (activePrimePowerFinset c)
    (fun n => coeff n * Real.cos (t * Real.log (n : ℝ)))

/-- Uniform coefficient bound for the finite prime trigonometric correction. -/
noncomputable def finitePrimeTrigBound
    (c : ℝ) (coeff : ℕ → ℝ) : ℝ :=
  Finset.sum (activePrimePowerFinset c)
    (fun n => |coeff n|)

theorem finitePrimeTrigBound_nonneg
    (c : ℝ) (coeff : ℕ → ℝ) :
    0 ≤ finitePrimeTrigBound c coeff := by
  unfold finitePrimeTrigBound
  exact Finset.sum_nonneg fun n hn => abs_nonneg _

/--
A finite WD-T34 prime trigonometric polynomial is uniformly bounded by the
sum of the absolute values of its coefficients.
-/
theorem abs_finitePrimeTrigCorrection_le
    (c : ℝ) (coeff : ℕ → ℝ) (t : ℝ) :
    |finitePrimeTrigCorrection c coeff t|
      ≤ finitePrimeTrigBound c coeff := by
  unfold finitePrimeTrigCorrection finitePrimeTrigBound
  calc
    |Finset.sum (activePrimePowerFinset c)
        (fun n => coeff n * Real.cos (t * Real.log (n : ℝ)))|
        =
      ‖Finset.sum (activePrimePowerFinset c)
        (fun n => coeff n * Real.cos (t * Real.log (n : ℝ)))‖ := by
          simp only [Real.norm_eq_abs]
    _ ≤
      Finset.sum (activePrimePowerFinset c)
        (fun n => ‖coeff n * Real.cos (t * Real.log (n : ℝ))‖) :=
      norm_sum_le _ _
    _ ≤
      Finset.sum (activePrimePowerFinset c)
        (fun n => |coeff n|) := by
      apply Finset.sum_le_sum
      intro n hn
      rw [Real.norm_eq_abs, abs_mul]
      simpa using
        mul_le_mul_of_nonneg_left
          (Real.abs_cos_le_one (t * Real.log (n : ℝ)))
          (abs_nonneg (coeff n))

/--
The finite prime correction is order zero relative to the logarithmic
principal weight.
-/
theorem finitePrimeTrigCorrection_isBigO_logarithmic
    (c : ℝ) (coeff : ℕ → ℝ) :
    finitePrimeTrigCorrection c coeff
      =O[atTop] logarithmicFourierWeight := by
  let B := finitePrimeTrigBound c coeff
  have hB : 0 ≤ B := finitePrimeTrigBound_nonneg c coeff
  apply IsBigO.of_bound B
  filter_upwards with t
  have hw1 := one_le_logarithmicFourierWeight t
  have hw0 : 0 ≤ logarithmicFourierWeight t :=
    zero_le_one.trans hw1
  have hc :=
    abs_finitePrimeTrigCorrection_le c coeff t
  rw [Real.norm_eq_abs, Real.norm_eq_abs, abs_of_nonneg hw0]
  exact hc.trans (by nlinarith)

/--
Adding the finite WD-T34 prime correction does not change the logarithmic
principal order.
-/
theorem logarithmicPlusFinitePrimeCorrection_isBigO
    (c : ℝ) (coeff : ℕ → ℝ) :
    (fun t : ℝ =>
      logarithmicFourierWeight t
        + finitePrimeTrigCorrection c coeff t)
      =O[atTop] logarithmicFourierWeight := by
  let B := finitePrimeTrigBound c coeff
  have hB : 0 ≤ B := finitePrimeTrigBound_nonneg c coeff
  apply IsBigO.of_bound (1 + B)
  filter_upwards with t
  have hw1 := one_le_logarithmicFourierWeight t
  have hw0 : 0 ≤ logarithmicFourierWeight t :=
    zero_le_one.trans hw1
  have hc :=
    abs_finitePrimeTrigCorrection_le c coeff t
  calc
    ‖logarithmicFourierWeight t
        + finitePrimeTrigCorrection c coeff t‖
        ≤ ‖logarithmicFourierWeight t‖
          + ‖finitePrimeTrigCorrection c coeff t‖ :=
      norm_add_le _ _
    _ ≤ logarithmicFourierWeight t + B := by
      rw [Real.norm_eq_abs, abs_of_nonneg hw0, Real.norm_eq_abs]
      exact add_le_add le_rfl hc
    _ ≤ (1 + B) * ‖logarithmicFourierWeight t‖ := by
      rw [Real.norm_eq_abs, abs_of_nonneg hw0]
      nlinarith

/--
Finite prime translations cannot repair the WD-T36 positive-order mismatch:
even after any fixed WD-T34 cosine correction, the positive Sobolev frequency
weight is not uniformly controlled.
-/
theorem wd_t36_finite_prime_translations_add_no_smoothing
    {eps : ℝ} (heps : 0 < eps)
    (c : ℝ) (coeff : ℕ → ℝ) :
    ¬ (fun x : ℝ => positiveSobolevFrequencyWeight eps x)
        =O[atTop]
      (fun t : ℝ =>
        logarithmicFourierWeight t
          + finitePrimeTrigCorrection c coeff t) := by
  intro h
  apply positiveSobolevFrequencyWeight_not_isBigO_logarithmic heps
  exact h.trans
    (logarithmicPlusFinitePrimeCorrection_isBigO c coeff)

end WeilDefect
