"""NF49: all remaining signed complete source Grams on unchanged P,T53,H.

Existing high minorants give a joint Loewner LOWER bound. A negative value
of that lower bound rejects the bound, never the original Weil form.
"""
import argparse,base64,gzip,hashlib,json,pickle,sys,os
from fractions import Fraction as F
from decimal import Decimal as D,localcontext
from pathlib import Path
sys.set_int_max_str_digits(0)
import certify_native_remaining_native_nf48_106 as native
import native_transport_nf49_moments as fast
v=native.v;f=native.f;n=v.n;I=v.I;dot=v.p.dot;mv=v.p.mv;K=v.K


def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def ends(matrix):return [[z.ends() for z in row] for row in matrix]
def upper(matrix):return [matrix[i][j].ends() for i in range(len(matrix)) for j in range(i,len(matrix))]


def packet(idx):
    if idx==0:
        o,H,*_=v.packet(0)
        cert=f.data('EVEN_NEXT_SHELL_CERTIFICATE',46)
        trial=f.data('EVEN_FIXED_NEXT_SHELL',46)
        lo,errors=v.high_projection_data(0,o,v.parents()[2]);label='eighth';count='eight'
    else:
        o,H,*_=v.prior.packet(1)
        cert=f.data('ODD_INVERSE_WITNESS_CERTIFICATE',45)
        trial=f.data('ODD_FIXED_INVERSE_WITNESS',45)
        lo,errors=v.prior.high_projection_data(1,o,v.prior.parents()[3]);label='seventh';count='seven'
    H=H+[(trial['selection_indices'],list(map(F,trial['fixed_rational_'+label+'_high_coefficients']))) ]
    co=dict(zip(cert['reconstructed_'+label+'_source_coordinates_indices'],map(v.p.iv,cert['reconstructed_'+label+'_source_coordinates'])))
    lo.append([co[j] for j in o['ids']]);errors.append(F(cert[label+'_projected_source_error_upper']))
    matrices=[v.p.prev.matrix(cert[key]) for key in [count+'_high_physical_Gram',count+'_high_native_Gram',
        count+'_high_complete_source_Gram','joined_'+count+'_high_native_crosses','joined_'+count+'_high_source_crosses']]
    assert len(H)==len(lo)==len(errors)==8-idx
    return o,H,lo,errors,matrices,cert


def cached(path,key,builder):
    # These private caches contain only objects generated by this script in
    # work/. They are not repository or uploaded input artifacts.
    if path.is_file():
        try:
            saved=pickle.loads(path.read_bytes())
            if saved['key']==key:return saved['value']
        except (EOFError,pickle.UnpicklingError,OSError):pass
    value=builder();temporary=path.with_name(path.name+'.tmp.'+str(os.getpid()))
    temporary.write_bytes(pickle.dumps(dict(key=key,value=value),protocol=5));os.replace(temporary,path);return value


def lower_sign(matrix,physical):
    size=len(matrix)
    with localcontext() as context:
        context.prec=190
        def dec(z):z=F(z);return D(z.numerator)/D(z.denominator)
        a=[[dec(z.mid()) for z in row] for row in matrix]
        L=[[D(int(i==j)) for j in range(size)] for i in range(size)];piv=[]
        for k in range(size):
            value=a[k][k]-sum((L[k][j]**2*piv[j] for j in range(k)),D(0))
            if value<=0:
                w=[D(0)]*size;w[k]=D(1)
                for j in reversed(range(k)):w[j]=-sum((L[i][j]*w[i] for i in range(j+1,k+1)),D(0))
                rational=[F((z*D(10)**100).to_integral_value(rounding='ROUND_FLOOR'))/10**100 for z in w]
                value=dot(rational,mv(matrix,rational))
                coeff={}
                for scalar,(ids,col) in zip(rational,physical):
                    for j,c in zip(ids,col):coeff[j]=coeff.get(j,F(0))+scalar*c
                mass=sum(c*c for c in coeff.values());assert mass>0
                if value.h<0:return dict(status='JOINT_LOWER_BOUND_REJECTED',fixed_rational_lower_bound_witness=list(map(str,rational)),
                    witness_original_physical_mass_squared=str(mass),witness_lower_matrix_value=value.ends(),
                    witness_lower_matrix_physical_quotient=(value/mass).ends(),first_nonpositive_midpoint_LDL_pivot=k,
                    actual_negative_original_vector_claimed=False)
                return dict(status='UNRESOLVED',first_nonpositive_midpoint_LDL_pivot=k,actual_negative_original_vector_claimed=False)
            piv.append(value)
            for i in range(k+1,size):L[i][k]=(a[i][k]-sum((L[i][j]*L[k][j]*piv[j] for j in range(k)),D(0)))/value
    try:_,proof=v.mi.inverse(matrix)
    except AssertionError:
        return dict(status='UNRESOLVED',all_midpoint_LDL_pivots_positive=True,
                    positive_rational_congruence_not_certified=True,actual_negative_original_vector_claimed=False)
    return dict(status='CERTIFIED_POSITIVE_JOINT_LOWER_BOUND',positive_congruence_proof=proof,actual_negative_original_vector_claimed=False)


def run(parity):
    idx=['even','odd'].index(parity)
    data,source,archive_hashes=f.frame.inputs()
    nf47=json.loads(Path('notes/data/RPB108_NF47_FLOOR_TRANSPORT_CERTIFICATE_20261009.json').read_bytes())
    nf48=native.decode('notes/data/RPB108_NF48_REMAINING_NATIVE_CERTIFICATE_20261009.json.gz.b64')
    old=nf48['parity_certificates'][idx];ids,T,retained,P=native.constraint_frame(nf47['parity_frames'][idx])
    o,H,loH,eH,(MH,QH,GH,BH,SH),oldpacket=packet(idx)
    assert P==o['columns'] and ids==o['ids']
    cols=list(zip(*T));Tphysical=[(ids,list(col)) for col in cols]
    def Q(i,j):return I(*map(F,source[f'{min(i,j)},{max(i,j)}']['full']))
    lowT=[[sum((c*Q(i,j) for i,c in zip(ids,col) if c),I(0)) for j in ids] for col in cols]
    allphysical=Tphysical+P+H;low=lowT+o['low']+loH
    key=hashlib.sha256(repr((parity,allphysical,[[z.ends() for z in r] for r in low],1100,n.SCALE,
        [sha('scripts/'+name) for name in ['certify_native_correlated_sources_nf25_106.py','certify_native_high_correction_nf26_106.py',
                                        'certify_native_expanded_response_nf30_106.py','certify_native_remaining_source_probe_nf32_106.py']])).encode()).hexdigest()
    work=Path('work/nf49')/parity;work.mkdir(parents=True,exist_ok=True)
    m=cached(work/'moments.pkl',key,lambda:v.p.p.old.probe.Moments(1100,parity))
    print(parity,'historical endpoint moments ready',flush=True)
    sources=[]
    for j,((ii,cc),projection) in enumerate(zip(allphysical,low)):
        s=cached(work/f'source_{j:02d}.pkl',key,lambda ii=ii,cc=cc,projection=projection:
            v.r.projection(m.source(ii,cc),projection,ids))
        sources.append(s);print(parity,'complete source constructed',j+1,'/',len(allphysical),flush=True)
    masses=[v.ceilnorm(col) for _,col in Tphysical]
    eT=[m.eta*mass+8*max(F(z.h-z.l,2*n.SCALE) for z in projection) for mass,projection in zip(masses,lowT)]
    bcount=max(len(s[1]) for s in sources);lcount=max(len(s[2]) for s in sources);ccount=max(len(c) for s in sources for c in s[3])
    rawTT=[[None]*53 for _ in range(53)];rawTP=[[None]*3 for _ in range(53)];rawTH=[[None]*len(H) for _ in range(53)]
    for j in range(53):
        adj=cached(work/f'adjoint_{j:02d}.pkl',key+'-'+sha('scripts/native_transport_nf49_moments.py'),
                   lambda j=j:fast.adjoint(sources[j],m,bcount,lcount,ccount))
        for i in range(j+1):rawTT[i][j]=rawTT[j][i]=fast.gram(sources[i],adj)
        for k in range(3):rawTP[j][k]=fast.gram(sources[53+k],adj)
        for k in range(len(H)):rawTH[j][k]=fast.gram(sources[56+k],adj)
        print(parity,'all signed covariances on remaining column',j+1,'/ 53',flush=True)
    normsT=[v.r.normupper(rawTT[j][j]) for j in range(53)]
    normsP=[v.r.normupper(oG)+e for oG,e in zip([v.p.prev.matrix(o['parent37']['original_selected_complete_source_Gram'])[i][i] for i in range(3)],o['physical_source_errors'])]
    normsH=[v.r.normupper(GH[j][j])+eH[j] for j in range(len(H))]
    def pay(raw,ea,eb,na,nb):return [[z+I(-(ea[i]*nb[j]+eb[j]*na[i]+ea[i]*eb[j]),ea[i]*nb[j]+eb[j]*na[i]+ea[i]*eb[j]) for j,z in enumerate(row)] for i,row in enumerate(raw)]
    TT=pay(rawTT,eT,eT,normsT,normsT);TP=pay(rawTP,eT,o['physical_source_errors'],normsT,normsP);TH=pay(rawTH,eT,eH,normsT,normsH)
    nativeTH=[[dot(col,loH[j])+I(-eH[j]*masses[i],eH[j]*masses[i]) for j in range(len(H))] for i,col in enumerate(cols)]
    checks=[]
    # Historical pairwise integration is deliberately retained for independent
    # end-to-end checks of diagonal, signed and mixed-log/cell adjoints.
    n.product=v.r.packed_product
    for a,b in [(0,0),(0,52),(52,52),(0,53),(52,56)]:
        direct=m.gram(sources[a],sources[b]);batched=rawTT[a][b] if b<53 else rawTP[a][b-53] if b<56 else rawTH[a][b-56]
        assert max(direct.l,batched.l)<=min(direct.h,batched.h)
        checks.append(dict(source_indices=[a,b],historical=direct.ends(),batched=batched.ends(),overlap=True))
        print(parity,'historical direct Gram check',a,b,'PASS',flush=True)
    GP=v.p.prev.matrix(o['parent37']['original_selected_complete_source_Gram']);QP=v.p.prev.matrix(o['parent37']['original_selected_native_energy_Gram'])
    C=v.p.prev.matrix(old['original_remaining_native_Gram']);B0=v.c.tr(v.p.prev.matrix(old['original_remaining_native_couplings']))
    fullQ=v.block(QP,v.c.tr(B0),B0,C);fullG=v.block(GP,v.c.tr(TP),TP,TT)
    fullB=BH+nativeTH;fullS=SH+TH
    _,_,W,N,NI,reaction,cp,np=v.inverse_packet(MH,QH,GH,fullB,fullS,fullG)
    lower=v.symmetry(v.c.add(fullQ,v.c.scale(reaction,-1)))
    for i in range(3):
        for j in range(3):assert lower[i][j].ends()==oldpacket['conditional_'+('eight' if idx==0 else 'seven')+'_high_joined_Schur_lower_matrix'][i][j]
    sign=lower_sign(lower,P+Tphysical)
    print(parity,sign['status'],flush=True)
    return dict(milestone='NF49',parity=parity,aperture='53/50',original_archive_uncompressed_sha256=archive_hashes,
        frozen_input_sha256={p:sha(p) for p in ['notes/data/RPB108_NF47_FLOOR_TRANSPORT_CERTIFICATE_20261009.json',
           'notes/data/RPB108_NF48_REMAINING_NATIVE_CERTIFICATE_20261009.json.gz.b64','notes/data/RPB108_NF48_REMAINING_NATIVE_VALIDATION_20261009.json']},
        original_remaining_dimension=53,existing_high_minorant_dimension=len(H),regular_kernel_N=320,pole_degree=40,
        original_translation_cells=len(m.cm),interval_grid_digits=500,source_analytic_unit_error=str(m.eta),
        remaining_source_physical_errors=list(map(str,eT)),remaining_source_approximant_norm_upper=list(map(str,normsT)),
        joined_source_physical_errors=list(map(str,o['physical_source_errors'])),joined_source_approximant_norm_upper=list(map(str,normsP)),
        high_source_physical_errors=list(map(str,eH)),high_source_approximant_norm_upper=list(map(str,normsH)),
        reconstructed_remaining_source_Gram_upper=upper(rawTT),original_remaining_complete_source_Gram_upper=upper(TT),
        reconstructed_remaining_joined_source_crosses=ends(rawTP),original_remaining_joined_source_crosses=ends(TP),
        reconstructed_remaining_high_source_crosses=ends(rawTH),original_remaining_high_source_crosses=ends(TH),
        original_remaining_high_native_crosses=ends(nativeTH),original_remaining_surplus_source_crosses=ends(v.c.add(TH,v.c.scale(nativeTH,-K))),
        all_remaining_source_Gram_entries_certified=1431,all_signed_joined_source_crosses_certified=159,
        all_signed_existing_high_source_crosses_certified=53*len(H),
        complete_joint_high_inverse_upper_upper_triangle=upper(reaction),complete_joint_original_Schur_lower_upper_triangle=upper(lower),
        joint_surplus_positive_proof=cp,joint_inverse_denominator_positive_proof=np,
        original_fixed_joined_block_preserved_exactly=True,historical_direct_Gram_checks=checks,arithmetic_controls=fast.controls(),
        joint_lower_bound_sign=sign,source_analytic_infinite_remainders_paid=True,
        complete_remaining_source_transport_data_certified=True,parity_whole_form_positive=sign['status']=='CERTIFIED_POSITIVE_JOINT_LOWER_BOUND',
        whole_aperture_positive=False,
        actual_negative_original_form_claimed=False,original_frozen_vectors_changed=False,original_inputs_regenerated=False,
        highest_certified_whole_aperture='21/20',RH=False,F4=False,Lean=False)


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--parity',choices=['even','odd'],required=True);p.add_argument('--output',required=True);a=p.parse_args()
    raw=(json.dumps(run(a.parity),indent=2,sort_keys=True)+'\n').encode()
    Path(a.output).write_bytes(base64.b64encode(gzip.compress(raw,mtime=0))+b'\n')
