import WeilDefect.Morphology.NeutralGaussianPairing

namespace WeilDefect

noncomputable section

open MeasureTheory Filter
open scoped SchwartzMap Topology


/--
Source-faithful whole-line growth carrier for the explicit pole/evaluation
component.

For the actual compact-window Weil formula this species is finite-dimensional
and generated by fixed real exponentials, so an exponential growth bound is
the exact analytic datum needed for Gaussian pairing.
-/
structure NeutralPoleExponentialGrowthData
    (pole : ℝ → ℂ) where
  pole_locallyIntegrable : LocallyIntegrable pole volume
  growthConstant : ℝ
  growthRate : ℝ
  growthConstant_nonneg : 0 ≤ growthConstant
  growthRate_nonneg : 0 ≤ growthRate
  growth_bound :
    ∀ x : ℝ,
      ‖pole x‖
        ≤ growthConstant * Real.exp (growthRate * |x|)

/--
F-4 domain bridge for the one noncompact test family used by WD-T40.

This structure strengthens the existing compact-test EXT-4 realization only
enough to admit the actual moving-Gaussian filtered mode.  It deliberately
contains no logarithmic coercivity or downstream Fourier-decay statement.
-/
structure RightLimitWeilGaussianAdmissibilityBridge
    (c : ℝ)
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    (carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs)
    (residual : NeutralExponentialResidualCarrier c)
    (hSymbol : RightLimitWeilSymbolTemperatePremise residual.a)
    (pole : ℝ → ℂ)
    (Ck : ℂ)
    (R : ℝ) where
  compactWeak :
    RightLimitWeilWeakRealizationPremise
      c carrier residual hSymbol pole
  gaussianTest : SchwartzMap ℝ ℂ
  gaussianTest_apply :
    ∀ x : ℝ,
      gaussianTest x =
        movingGaussianFilteredMode Ck R carrier x
  residual_pairing_integrable :
    Integrable
      (fun x : ℝ =>
        gaussianTest x * residual.q x) volume
  pole_pairing_integrable :
    Integrable
      (fun x : ℝ =>
        gaussianTest x * pole x) volume
  gaussianWeakIdentity :
    (∫ x : ℝ,
      gaussianTest x * residual.q x ∂volume)
      =
    rightLimitWeilMultiplierCore
        residual.a hSymbol carrier.temperedMode gaussianTest
      +
    ∫ x : ℝ,
      gaussianTest x * pole x ∂volume


/--
Completed Gaussian-tail domination for an explicit pole/evaluation term with
fixed exponential growth.
-/
theorem poleFilteredMode_norm_le_completedTail
    {c : ℝ}
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    (carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs)
    (residual : NeutralExponentialResidualCarrier c)
    (pole : ℝ → ℂ)
    (hpole : NeutralPoleExponentialGrowthData pole)
    (Ck : ℂ) {R x : ℝ}
    (hc : 0 ≤ c)
    (hR : 0 ≤ R)
    (hlarge :
      8 * hpole.growthRate
        ≤ R * (residual.a - c))
    (hx : x ∉ Set.Ioo (-residual.a) residual.a) :
    ‖pole x * movingGaussianFilteredMode Ck R carrier x‖
      ≤
    (hpole.growthConstant
      * (‖Ck‖ * Real.sqrt R)
      * neutralPhysicalCompactL1Mass carrier
      * Real.exp (hpole.growthRate * c)
      * Real.exp (-R * (residual.a - c) ^ 2 / 16))
      * Real.exp (-R * (|x| - c) ^ 2 / 16) := by
  have hfiltered :=
    movingGaussianFilteredMode_norm_le_exteriorEnvelope
      carrier residual Ck R x hc hR hx
  have hcompletion :=
    gaussianTailCompletion_bound
      hpole.growthRate_nonneg hR hc residual.strict
      hlarge hx
  rw [norm_mul]
  calc
    ‖pole x‖ * ‖movingGaussianFilteredMode Ck R carrier x‖
      ≤
    (hpole.growthConstant
      * Real.exp (hpole.growthRate * |x|))
      *
    ((‖Ck‖ * Real.sqrt R
      * gaussianSupportEnvelope R c x)
      * neutralPhysicalCompactL1Mass carrier) := by
        exact mul_le_mul
          (hpole.growth_bound x)
          hfiltered
          (norm_nonneg _)
          (mul_nonneg
            hpole.growthConstant_nonneg
            (Real.exp_nonneg _))
    _ ≤
    (hpole.growthConstant
      * (‖Ck‖ * Real.sqrt R)
      * neutralPhysicalCompactL1Mass carrier
      * Real.exp (hpole.growthRate * c)
      * Real.exp (-R * (residual.a - c) ^ 2 / 16))
      * Real.exp (-R * (|x| - c) ^ 2 / 16) := by
        have hkernel : 0 ≤ ‖Ck‖ * Real.sqrt R :=
          mul_nonneg (norm_nonneg Ck) (Real.sqrt_nonneg R)
        have hnonneg :
            0 ≤ hpole.growthConstant
              * (‖Ck‖ * Real.sqrt R)
              * neutralPhysicalCompactL1Mass carrier :=
          mul_nonneg
            (mul_nonneg hpole.growthConstant_nonneg hkernel)
            (neutralPhysicalCompactL1Mass_nonneg carrier)
        nlinarith [hcompletion]

/--
The explicit exponential-growth pole term pairs integrably with the actual
moving-Gaussian filtered mode.
-/
theorem poleFilteredMode_integrable
    {c : ℝ}
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    (carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs)
    (residual : NeutralExponentialResidualCarrier c)
    (pole : ℝ → ℂ)
    (hpole : NeutralPoleExponentialGrowthData pole)
    (Ck : ℂ) {R : ℝ}
    (hc : 0 ≤ c)
    (hR : 0 < R)
    (hlarge :
      8 * hpole.growthRate
        ≤ R * (residual.a - c)) :
    Integrable
      (fun x : ℝ =>
        pole x * movingGaussianFilteredMode Ck R carrier x) volume := by
  let A : ℝ :=
    hpole.growthConstant
      * (‖Ck‖ * Real.sqrt R)
      * neutralPhysicalCompactL1Mass carrier
      * Real.exp (hpole.growthRate * c)
      * Real.exp (-R * (residual.a - c) ^ 2 / 16)
  have hA : 0 ≤ A := by
    dsimp [A]
    have hkernel : 0 ≤ ‖Ck‖ * Real.sqrt R :=
      mul_nonneg (norm_nonneg Ck) (Real.sqrt_nonneg R)
    have h₁ :
        0 ≤ hpole.growthConstant
          * (‖Ck‖ * Real.sqrt R)
          * neutralPhysicalCompactL1Mass carrier :=
      mul_nonneg
        (mul_nonneg hpole.growthConstant_nonneg hkernel)
        (neutralPhysicalCompactL1Mass_nonneg carrier)
    exact mul_nonneg
      (mul_nonneg h₁ (Real.exp_nonneg _))
      (Real.exp_nonneg _)
  have hext :
      IntegrableOn
        (fun x : ℝ =>
          pole x * movingGaussianFilteredMode Ck R carrier x)
        (gaussianExteriorSet residual.a) volume := by
    have htail :
        IntegrableOn
          (fun x : ℝ =>
            A * Real.exp (-R * (|x| - c) ^ 2 / 16))
          (gaussianExteriorSet residual.a) volume :=
      (gaussianExteriorTail_integrableOn hR hc residual.strict).const_mul A
    have hfilteredMeas :
        AEStronglyMeasurable
          (movingGaussianFilteredMode Ck R carrier) volume :=
      (movingGaussianFilteredMode_continuous
        carrier Ck hR.le).aestronglyMeasurable
    have hpairMeas :
        AEStronglyMeasurable
          (fun x : ℝ =>
            pole x * movingGaussianFilteredMode Ck R carrier x) volume :=
      hpole.pole_locallyIntegrable.aestronglyMeasurable.mul hfilteredMeas
    apply Integrable.mono htail hpairMeas.restrict
    have hextMeas : MeasurableSet (gaussianExteriorSet residual.a) := by
      unfold gaussianExteriorSet
      exact measurableSet_Iic.union measurableSet_Ici
    filter_upwards [self_mem_ae_restrict hextMeas] with x hx
    have hxout :
        x ∉ Set.Ioo (-residual.a) residual.a := by
      rw [gaussianExteriorSet] at hx
      rcases hx with hxleft | hxright
      · exact fun hin => (not_lt_of_ge hxleft) hin.1
      · exact fun hin => (not_lt_of_ge hxright) hin.2
    have hbound :=
      poleFilteredMode_norm_le_completedTail
        carrier residual pole hpole Ck hc hR.le hlarge hxout
    have htailNonneg :
        0 ≤ A * Real.exp (-R * (|x| - c) ^ 2 / 16) :=
      mul_nonneg hA (Real.exp_nonneg _)
    rw [Real.norm_eq_abs, abs_of_nonneg htailNonneg]
    simpa [A] using hbound
  have hint :
      IntegrableOn
        (fun x : ℝ =>
          pole x * movingGaussianFilteredMode Ck R carrier x)
        (Set.Icc (-residual.a) residual.a) volume := by
    have hpoleInt :=
      hpole.pole_locallyIntegrable.integrableOn_isCompact isCompact_Icc
    exact hpoleInt.mul_continuousOn
      (movingGaussianFilteredMode_continuous
        carrier Ck hR.le).continuousOn
      isCompact_Icc
  have hall :
      IntegrableOn
        (fun x : ℝ =>
          pole x * movingGaussianFilteredMode Ck R carrier x)
        (Set.Icc (-residual.a) residual.a
          ∪ gaussianExteriorSet residual.a) volume :=
    hint.union hext
  have hunion :
      Set.Icc (-residual.a) residual.a
          ∪ gaussianExteriorSet residual.a
        = Set.univ := by
    ext x
    simp [gaussianExteriorSet]
    by_cases hx : x < -residual.a
    · right
      left
      exact le_of_lt hx
    · by_cases hx' : residual.a < x
      · right
        right
        exact le_of_lt hx'
      · left
        exact ⟨le_of_not_gt hx, le_of_not_gt hx'⟩
  rw [hunion] at hall
  exact integrableOn_univ.mp hall

namespace RightLimitWeilGaussianAdmissibilityBridge

variable
    {c : ℝ}
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    {carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs}
    {residual : NeutralExponentialResidualCarrier c}
    {hSymbol : RightLimitWeilSymbolTemperatePremise residual.a}
    {pole : ℝ → ℂ}
    {Ck : ℂ}
    {R : ℝ}

/--
The physical F-3 pairing is exactly the left-hand side of the admissible
Gaussian weak identity.
-/
theorem movingGaussianResidualPairing_eq_weakLeft
    (d :
      RightLimitWeilGaussianAdmissibilityBridge
        c carrier residual hSymbol pole Ck R) :
    movingGaussianResidualPairing carrier residual Ck R
      =
    ∫ x : ℝ,
      d.gaussianTest x * residual.q x ∂volume := by
  unfold movingGaussianResidualPairing
  apply integral_congr_ae
  filter_upwards with x
  rw [d.gaussianTest_apply x]
  exact mul_comm _ _

/--
Typed F-4 domain bridge.

It exposes the two required integrability statements and transfers the
compact-test EXT-4 realization to the actual moving-Gaussian test without
asserting any coercive estimate.
-/
theorem gaussianWeakRealization
    (d :
      RightLimitWeilGaussianAdmissibilityBridge
        c carrier residual hSymbol pole Ck R) :
    Integrable
        (fun x : ℝ =>
          d.gaussianTest x * residual.q x) volume
      ∧
    Integrable
        (fun x : ℝ =>
          d.gaussianTest x * pole x) volume
      ∧
    movingGaussianResidualPairing carrier residual Ck R
      =
    rightLimitWeilMultiplierCore
        residual.a hSymbol carrier.temperedMode d.gaussianTest
      +
    ∫ x : ℝ,
      d.gaussianTest x * pole x ∂volume := by
  refine ⟨d.residual_pairing_integrable, d.pole_pairing_integrable, ?_⟩
  rw [d.movingGaussianResidualPairing_eq_weakLeft]
  exact d.gaussianWeakIdentity

/--
Forget Gaussian admissibility and recover the already-certified compact-test
EXT-4 realization premise.
-/
def toCompactWeak
    (d :
      RightLimitWeilGaussianAdmissibilityBridge
        c carrier residual hSymbol pole Ck R) :
    RightLimitWeilWeakRealizationPremise
      c carrier residual hSymbol pole :=
  d.compactWeak

end RightLimitWeilGaussianAdmissibilityBridge


/--
Cutoff package sufficient to derive Gaussian admissibility from the existing
compact-test EXT-4 realization.

The only noncompact identity is obtained as a limit of compactly supported
Schwartz tests; it is not stored as an assumption here.
-/
structure RightLimitWeilGaussianCutoffPremise
    (c : ℝ)
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    (carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs)
    (residual : NeutralExponentialResidualCarrier c)
    (pole : ℝ → ℂ)
    (Ck : ℂ)
    (R : ℝ) where
  gaussianTest : SchwartzMap ℝ ℂ
  gaussianTest_apply :
    ∀ x : ℝ,
      gaussianTest x =
        movingGaussianFilteredMode Ck R carrier x
  cutoff : ℕ → SchwartzMap ℝ ℂ
  cutoff_compact :
    ∀ n : ℕ, HasCompactSupport (cutoff n)
  cutoff_tendsto :
    Tendsto cutoff atTop (𝓝 gaussianTest)
  residual_pairing_integrable :
    Integrable
      (fun x : ℝ =>
        gaussianTest x * residual.q x) volume
  pole_pairing_integrable :
    Integrable
      (fun x : ℝ =>
        gaussianTest x * pole x) volume
  residual_pairing_tendsto :
    Tendsto
      (fun n : ℕ =>
        ∫ x : ℝ, cutoff n x * residual.q x ∂volume)
      atTop
      (𝓝
        (∫ x : ℝ,
          gaussianTest x * residual.q x ∂volume))
  pole_pairing_tendsto :
    Tendsto
      (fun n : ℕ =>
        ∫ x : ℝ, cutoff n x * pole x ∂volume)
      atTop
      (𝓝
        (∫ x : ℝ,
          gaussianTest x * pole x ∂volume))

namespace RightLimitWeilGaussianCutoffPremise

variable
    {c : ℝ}
    {EndpointObs RightObs : Type*}
    [NormedAddCommGroup EndpointObs] [NormedSpace ℂ EndpointObs]
    [NormedAddCommGroup RightObs] [NormedSpace ℂ RightObs]
    {carrier : NeutralPhysicalFourierCarrier c EndpointObs RightObs}
    {residual : NeutralExponentialResidualCarrier c}
    {hSymbol : RightLimitWeilSymbolTemperatePremise residual.a}
    {pole : ℝ → ℂ}
    {Ck : ℂ}
    {R : ℝ}

/--
Termwise compact-test EXT-4 plus cutoff convergence imply the weak identity
for the actual moving-Gaussian test.

The multiplier-core limit is internal: tempered distributions are continuous
linear functionals on Schwartz space.
-/
theorem gaussianWeakIdentity_of_cutoff
    (hcompact :
      RightLimitWeilWeakRealizationPremise
        c carrier residual hSymbol pole)
    (d :
      RightLimitWeilGaussianCutoffPremise
        c carrier residual pole Ck R) :
    (∫ x : ℝ,
      d.gaussianTest x * residual.q x ∂volume)
      =
    rightLimitWeilMultiplierCore
        residual.a hSymbol carrier.temperedMode d.gaussianTest
      +
    ∫ x : ℝ,
      d.gaussianTest x * pole x ∂volume := by
  let core :=
    rightLimitWeilMultiplierCore
      residual.a hSymbol carrier.temperedMode
  have hcore :
      Tendsto
        (fun n : ℕ => core (d.cutoff n))
        atTop
        (𝓝 (core d.gaussianTest)) :=
    core.continuous.continuousAt.tendsto.comp d.cutoff_tendsto
  have hright :
      Tendsto
        (fun n : ℕ =>
          core (d.cutoff n)
            + ∫ x : ℝ, d.cutoff n x * pole x ∂volume)
        atTop
        (𝓝
          (core d.gaussianTest
            + ∫ x : ℝ,
                d.gaussianTest x * pole x ∂volume)) :=
    hcore.add d.pole_pairing_tendsto
  have hleft :
      Tendsto
        (fun n : ℕ =>
          ∫ x : ℝ, d.cutoff n x * residual.q x ∂volume)
        atTop
        (𝓝
          (core d.gaussianTest
            + ∫ x : ℝ,
                d.gaussianTest x * pole x ∂volume)) := by
    refine hright.congr' ?_
    exact Eventually.of_forall fun n =>
      (hcompact.weakIdentity
        (d.cutoff n) (d.cutoff_compact n)).symm
  exact tendsto_nhds_unique
    d.residual_pairing_tendsto hleft

/--
Construct the build-certified Gaussian-admissibility bridge from compact EXT-4
and a cutoff package.

No coercive estimate is introduced here.
-/
noncomputable def toGaussianAdmissibilityBridge
    (hcompact :
      RightLimitWeilWeakRealizationPremise
        c carrier residual hSymbol pole)
    (d :
      RightLimitWeilGaussianCutoffPremise
        c carrier residual pole Ck R) :
    RightLimitWeilGaussianAdmissibilityBridge
      c carrier residual hSymbol pole Ck R := {
  compactWeak := hcompact
  gaussianTest := d.gaussianTest
  gaussianTest_apply := d.gaussianTest_apply
  residual_pairing_integrable := d.residual_pairing_integrable
  pole_pairing_integrable := d.pole_pairing_integrable
  gaussianWeakIdentity :=
    gaussianWeakIdentity_of_cutoff hcompact d
}

end RightLimitWeilGaussianCutoffPremise

end

end WeilDefect
